version: '3.1'

services:
  ftp_server:
    env_file: .env
    container_name: "ftp_server"
    build:
      context: .
      dockerfile: ./docker_file/Dockerfile.server
    ports:
      - "8787:21"
    mac_address: ${MAC_1}
    networks:
      app_net:
        ipv4_address: ${IP_1}

  ftp_client:
    env_file: .env
    container_name: "ftp_client"
    build:
      context: .
      dockerfile: ./docker_file/Dockerfile.client
    mac_address: ${MAC_2}
    networks:
      app_net:
        ipv4_address: ${IP_2}

  inquisitor:
    env_file: .env
    container_name: "inquisitor"
    build:
      context: .
      dockerfile: ./docker_file/Dockerfile.inquisitor
    mac_address: "02:42:ac:11:00:04"
    networks:
      app_net:
        ipv4_address: 172.16.238.30

networks:
  app_net:
    ipam:
      config:
        - subnet: 172.16.238.0/24