version: '3.1'

services:
  ftp_server:
    env_file: .env
    privileged: true
    container_name: "ftp_server"
    build:
      context: .
      dockerfile: ./docker_file/Dockerfile.server
    ports:
      - "8787:21"
    mac_address: 02:42:ac:11:00:02
    cap_add:
      - NET_ADMIN
    networks:
      app_net:
        ipv4_address: 172.16.238.10

  ftp_client:
    env_file: .env
    privileged: true
    container_name: "ftp_client"
    build:
      context: .
      dockerfile: ./docker_file/Dockerfile.client
    mac_address: 02:42:ac:11:00:03
    cap_add:
      - NET_ADMIN
    networks:
      app_net:
        ipv4_address: 172.16.238.20

  inquisitor:
    env_file: .env
    container_name: "inquisitor"
    privileged: true
    build:
      context: .
      dockerfile: ./docker_file/Dockerfile.inquisitor
    mac_address: "02:42:ac:11:00:04"
    cap_add:
      - NET_ADMIN
    networks:
      app_net:
        ipv4_address: 172.16.238.30

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24