version: '3.1'

services:
  ftp_server:
    env_file: .env
    privileged: true
    container_name: "ftp_server"
    build:
      context: .
      dockerfile: ./docker_file/Dockerfile.server
    mac_address: ${MAC_SERVER}
    networks:
      app_net:
        ipv4_address: ${IP_SERVER}

  ftp_client:
    env_file: .env
    privileged: true
    container_name: "ftp_client"
    build:
      context: .
      dockerfile: ./docker_file/Dockerfile.client
    mac_address: ${MAC_CLIENT}
    networks:
      app_net:
        ipv4_address: ${IP_CLIENT}

  inquisitor:
    env_file: .env
    container_name: "inquisitor"
    privileged: true
    build:
      context: .
      dockerfile: ./docker_file/Dockerfile.inquisitor
    mac_address: "02:42:ac:11:00:04"
    networks:
      app_net:
        ipv4_address: 172.16.238.30

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24