
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/sgoinfre/goinfre/Perso/loumouli/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 5.15.0-84-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/sgoinfre/goinfre/Perso/loumouli/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/sgoinfre/goinfre/Perso/loumouli/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/sgoinfre/goinfre/Perso/loumouli/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/cc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is Clang, found in:
        /mnt/nfs/homes/loumouli/cybersecurity_pool_42/inquisitor/cmake-build-debug/CMakeFiles/3.26.4/CompilerIdC/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/sgoinfre/goinfre/Perso/loumouli/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/sgoinfre/goinfre/Perso/loumouli/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/mnt/nfs/homes/loumouli/cybersecurity_pool_42/inquisitor/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-CmnVta"
      binary: "/mnt/nfs/homes/loumouli/cybersecurity_pool_42/inquisitor/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-CmnVta"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: /mnt/nfs/homes/loumouli/cybersecurity_pool_42/inquisitor/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-CmnVta
        
        Run Build Command(s):/sgoinfre/goinfre/Perso/loumouli/clion/bin/ninja/linux/x64/ninja -v cmTC_b9ab3 && [1/2] /usr/bin/cc   -fcolor-diagnostics   -v -MD -MT CMakeFiles/cmTC_b9ab3.dir/CMakeCCompilerABI.c.o -MF CMakeFiles/cmTC_b9ab3.dir/CMakeCCompilerABI.c.o.d -o CMakeFiles/cmTC_b9ab3.dir/CMakeCCompilerABI.c.o -c /sgoinfre/goinfre/Perso/loumouli/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeCCompilerABI.c
        Ubuntu clang version 12.0.1-19ubuntu3
        Target: x86_64-pc-linux-gnu
        Thread model: posix
        InstalledDir: /usr/bin
        Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
        Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
        Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
        Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
        Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
        Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
        Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
        Candidate multilib: .;@m64
        Selected multilib: .;@m64
         (in-process)
         "/usr/lib/llvm-12/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -fno-split-dwarf-inlining -debugger-tuning=gdb -v -resource-dir /usr/lib/llvm-12/lib/clang/12.0.1 -dependency-file CMakeFiles/cmTC_b9ab3.dir/CMakeCCompilerABI.c.o.d -MT CMakeFiles/cmTC_b9ab3.dir/CMakeCCompilerABI.c.o -sys-header-deps -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-12/lib/clang/12.0.1/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir /mnt/nfs/homes/loumouli/cybersecurity_pool_42/inquisitor/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-CmnVta -ferror-limit 19 -fgnuc-version=4.2.1 -fcolor-diagnostics -faddrsig -o CMakeFiles/cmTC_b9ab3.dir/CMakeCCompilerABI.c.o -x c /sgoinfre/goinfre/Perso/loumouli/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeCCompilerABI.c
        clang -cc1 version 12.0.1 based upon LLVM 12.0.1 default target x86_64-pc-linux-gnu
        ignoring nonexistent directory "/include"
        #include "..." search starts here:
        #include <...> search starts here:
         /usr/local/include
         /usr/lib/llvm-12/lib/clang/12.0.1/include
         /usr/include/x86_64-linux-gnu
         /usr/include
        End of search list.
        [2/2] : && /usr/bin/cc  -v CMakeFiles/cmTC_b9ab3.dir/CMakeCCompilerABI.c.o -o cmTC_b9ab3   && :
        Ubuntu clang version 12.0.1-19ubuntu3
        Target: x86_64-pc-linux-gnu
        Thread model: posix
        InstalledDir: /usr/bin
        Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
        Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
        Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
        Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
        Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
        Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12
        Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12
        Candidate multilib: .;@m64
        Selected multilib: .;@m64
         "/usr/bin/ld" --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTC_b9ab3 /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/crt1.o /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/crti.o /usr/bin/../lib/gcc/x86_64-linux-gnu/12/crtbegin.o -L/usr/bin/../lib/gcc/x86_64-linux-gnu/12 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu -L/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/usr/lib/x86_64-linux-gnu/../../lib64 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../.. -L/usr/lib/llvm-12/bin/../lib -L/lib -L/usr/lib CMakeFiles/cmTC_b9ab3.dir/CMakeCCompilerABI.c.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/bin/../lib/gcc/x86_64-linux-gnu/12/crtend.o /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/crtn.o
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "/sgoinfre/goinfre/Perso/loumouli/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:127 (message)"
      - "/sgoinfre/goinfre/Perso/loumouli/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [/usr/local/include]
          add: [/usr/lib/llvm-12/lib/clang/12.0.1/include]
          add: [/usr/include/x86_64-linux-gnu]
          add: [/usr/include]
        end of search list found
        collapse include dir [/usr/local/include] ==> [/usr/local/include]
        collapse include dir [/usr/lib/llvm-12/lib/clang/12.0.1/include] ==> [/usr/lib/llvm-12/lib/clang/12.0.1/include]
        collapse include dir [/usr/include/x86_64-linux-gnu] ==> [/usr/include/x86_64-linux-gnu]
        collapse include dir [/usr/include] ==> [/usr/include]
        implicit include dirs: [/usr/local/include;/usr/lib/llvm-12/lib/clang/12.0.1/include;/usr/include/x86_64-linux-gnu;/usr/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/sgoinfre/goinfre/Perso/loumouli/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:152 (message)"
      - "/sgoinfre/goinfre/Perso/loumouli/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        ignore line: [Change Dir: /mnt/nfs/homes/loumouli/cybersecurity_pool_42/inquisitor/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-CmnVta]
        ignore line: []
        ignore line: [Run Build Command(s):/sgoinfre/goinfre/Perso/loumouli/clion/bin/ninja/linux/x64/ninja -v cmTC_b9ab3 && [1/2] /usr/bin/cc   -fcolor-diagnostics   -v -MD -MT CMakeFiles/cmTC_b9ab3.dir/CMakeCCompilerABI.c.o -MF CMakeFiles/cmTC_b9ab3.dir/CMakeCCompilerABI.c.o.d -o CMakeFiles/cmTC_b9ab3.dir/CMakeCCompilerABI.c.o -c /sgoinfre/goinfre/Perso/loumouli/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeCCompilerABI.c]
        ignore line: [Ubuntu clang version 12.0.1-19ubuntu3]
        ignore line: [Target: x86_64-pc-linux-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: /usr/bin]
        ignore line: [Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10]
        ignore line: [Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11]
        ignore line: [Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12]
        ignore line: [Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10]
        ignore line: [Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11]
        ignore line: [Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12]
        ignore line: [Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12]
        ignore line: [Candidate multilib: .]
        ignore line: [@m64]
        ignore line: [Selected multilib: .]
        ignore line: [@m64]
        ignore line: [ (in-process)]
        ignore line: [ "/usr/lib/llvm-12/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -fno-split-dwarf-inlining -debugger-tuning=gdb -v -resource-dir /usr/lib/llvm-12/lib/clang/12.0.1 -dependency-file CMakeFiles/cmTC_b9ab3.dir/CMakeCCompilerABI.c.o.d -MT CMakeFiles/cmTC_b9ab3.dir/CMakeCCompilerABI.c.o -sys-header-deps -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-12/lib/clang/12.0.1/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir /mnt/nfs/homes/loumouli/cybersecurity_pool_42/inquisitor/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-CmnVta -ferror-limit 19 -fgnuc-version=4.2.1 -fcolor-diagnostics -faddrsig -o CMakeFiles/cmTC_b9ab3.dir/CMakeCCompilerABI.c.o -x c /sgoinfre/goinfre/Perso/loumouli/clion/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeCCompilerABI.c]
        ignore line: [clang -cc1 version 12.0.1 based upon LLVM 12.0.1 default target x86_64-pc-linux-gnu]
        ignore line: [ignoring nonexistent directory "/include"]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ /usr/local/include]
        ignore line: [ /usr/lib/llvm-12/lib/clang/12.0.1/include]
        ignore line: [ /usr/include/x86_64-linux-gnu]
        ignore line: [ /usr/include]
        ignore line: [End of search list.]
        ignore line: [[2/2] : && /usr/bin/cc  -v CMakeFiles/cmTC_b9ab3.dir/CMakeCCompilerABI.c.o -o cmTC_b9ab3   && :]
        ignore line: [Ubuntu clang version 12.0.1-19ubuntu3]
        ignore line: [Target: x86_64-pc-linux-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: /usr/bin]
        ignore line: [Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10]
        ignore line: [Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11]
        ignore line: [Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12]
        ignore line: [Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10]
        ignore line: [Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11]
        ignore line: [Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/12]
        ignore line: [Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/12]
        ignore line: [Candidate multilib: .]
        ignore line: [@m64]
        ignore line: [Selected multilib: .]
        ignore line: [@m64]
        link line: [ "/usr/bin/ld" --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTC_b9ab3 /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/crt1.o /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/crti.o /usr/bin/../lib/gcc/x86_64-linux-gnu/12/crtbegin.o -L/usr/bin/../lib/gcc/x86_64-linux-gnu/12 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu -L/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/usr/lib/x86_64-linux-gnu/../../lib64 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../.. -L/usr/lib/llvm-12/bin/../lib -L/lib -L/usr/lib CMakeFiles/cmTC_b9ab3.dir/CMakeCCompilerABI.c.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/bin/../lib/gcc/x86_64-linux-gnu/12/crtend.o /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/crtn.o]
          arg [/usr/bin/ld] ==> ignore
          arg [--build-id] ==> ignore
          arg [--eh-frame-hdr] ==> ignore
          arg [-m] ==> ignore
          arg [elf_x86_64] ==> ignore
          arg [-dynamic-linker] ==> ignore
          arg [/lib64/ld-linux-x86-64.so.2] ==> ignore
          arg [-o] ==> ignore
          arg [cmTC_b9ab3] ==> ignore
          arg [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/crt1.o] ==> obj [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/crt1.o]
          arg [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/crti.o] ==> obj [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/crti.o]
          arg [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/crtbegin.o] ==> obj [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/crtbegin.o]
          arg [-L/usr/bin/../lib/gcc/x86_64-linux-gnu/12] ==> dir [/usr/bin/../lib/gcc/x86_64-linux-gnu/12]
          arg [-L/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu] ==> dir [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu]
          arg [-L/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../lib64] ==> dir [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../lib64]
          arg [-L/lib/x86_64-linux-gnu] ==> dir [/lib/x86_64-linux-gnu]
          arg [-L/lib/../lib64] ==> dir [/lib/../lib64]
          arg [-L/usr/lib/x86_64-linux-gnu] ==> dir [/usr/lib/x86_64-linux-gnu]
          arg [-L/usr/lib/../lib64] ==> dir [/usr/lib/../lib64]
          arg [-L/usr/lib/x86_64-linux-gnu/../../lib64] ==> dir [/usr/lib/x86_64-linux-gnu/../../lib64]
          arg [-L/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../..] ==> dir [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../..]
          arg [-L/usr/lib/llvm-12/bin/../lib] ==> dir [/usr/lib/llvm-12/bin/../lib]
          arg [-L/lib] ==> dir [/lib]
          arg [-L/usr/lib] ==> dir [/usr/lib]
          arg [CMakeFiles/cmTC_b9ab3.dir/CMakeCCompilerABI.c.o] ==> ignore
          arg [-lgcc] ==> lib [gcc]
          arg [--as-needed] ==> ignore
          arg [-lgcc_s] ==> lib [gcc_s]
          arg [--no-as-needed] ==> ignore
          arg [-lc] ==> lib [c]
          arg [-lgcc] ==> lib [gcc]
          arg [--as-needed] ==> ignore
          arg [-lgcc_s] ==> lib [gcc_s]
          arg [--no-as-needed] ==> ignore
          arg [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/crtend.o] ==> obj [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/crtend.o]
          arg [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/crtn.o] ==> obj [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/crtn.o]
        collapse obj [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/crt1.o] ==> [/usr/lib/x86_64-linux-gnu/crt1.o]
        collapse obj [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/crti.o] ==> [/usr/lib/x86_64-linux-gnu/crti.o]
        collapse obj [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/crtbegin.o] ==> [/usr/lib/gcc/x86_64-linux-gnu/12/crtbegin.o]
        collapse obj [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/crtend.o] ==> [/usr/lib/gcc/x86_64-linux-gnu/12/crtend.o]
        collapse obj [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/crtn.o] ==> [/usr/lib/x86_64-linux-gnu/crtn.o]
        collapse library dir [/usr/bin/../lib/gcc/x86_64-linux-gnu/12] ==> [/usr/lib/gcc/x86_64-linux-gnu/12]
        collapse library dir [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
        collapse library dir [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../lib64] ==> [/usr/lib64]
        collapse library dir [/lib/x86_64-linux-gnu] ==> [/lib/x86_64-linux-gnu]
        collapse library dir [/lib/../lib64] ==> [/lib64]
        collapse library dir [/usr/lib/x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
        collapse library dir [/usr/lib/../lib64] ==> [/usr/lib64]
        collapse library dir [/usr/lib/x86_64-linux-gnu/../../lib64] ==> [/usr/lib64]
        collapse library dir [/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../..] ==> [/usr/lib]
        collapse library dir [/usr/lib/llvm-12/bin/../lib] ==> [/usr/lib/llvm-12/lib]
        collapse library dir [/lib] ==> [/lib]
        collapse library dir [/usr/lib] ==> [/usr/lib]
        implicit libs: [gcc;gcc_s;c;gcc;gcc_s]
        implicit objs: [/usr/lib/x86_64-linux-gnu/crt1.o;/usr/lib/x86_64-linux-gnu/crti.o;/usr/lib/gcc/x86_64-linux-gnu/12/crtbegin.o;/usr/lib/gcc/x86_64-linux-gnu/12/crtend.o;/usr/lib/x86_64-linux-gnu/crtn.o]
        implicit dirs: [/usr/lib/gcc/x86_64-linux-gnu/12;/usr/lib/x86_64-linux-gnu;/usr/lib64;/lib/x86_64-linux-gnu;/lib64;/usr/lib;/usr/lib/llvm-12/lib;/lib]
        implicit fwks: []
      
      
...
