FROM debian:latest

RUN apt update && apt install -y net-tools iputils-ping vsftpd
RUN useradd -m ftpuser && echo "ftpuser:1234" | chpasswd
RUN mkdir -p /var/ftp && mkdir -p /var/run/vsftpd/empty

COPY vsftpd.conf /etc/vsftpd/

# CMD tail -f

CMD ["vsftpd", "/etc/vsftpd.conf"]
