FROM debian:latest

RUN apt update && apt install -y build-essential cmake libpcap-dev

WORKDIR /inquisitor

COPY ../inc ./inc
COPY ../CMakeLists.txt .
COPY ../run.sh .
COPY ../src ./src
RUN cmake -S . -B build && cmake --build build && mv ./build/inquisitor .

CMD tail -f