FROM debian:latest

RUN apt-get update && apt-get install -y fish tcpdump net-tools iputils-ping iproute2

RUN useradd -m ftpuser && echo "ftpuser:1234" | chpasswd

COPY vsftpd.conf /etc/vsftpd/

RUN mkdir -p /var/ftp && mkdir -p /var/run/vsftpd/empty

#CMD ["vsftpd", "/etc/vsftpd.conf"]
CMD tail -f