[package]
name = "iron_dome"
version = "0.1.0"
edition = "2021"

[dependencies]
daemonize = "0.5.0"
entropy = "0.4.1"
ctrlc = "3.4.1"
sysinfo = "0.29.10"

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
debug = true

[features]
dhat-heap = []