version: '3.1'

services:
  web:
    container_name: "web"
    build:
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - "5000:5000"
    networks:
      app_net:
  mariadb:
    container_name: "mariadb"
    build:
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prod
    networks:
      app_net:

networks:
  app_net: